### ISSUE TITLE
what's the embedding data format?

### ISSUE THREAD

**Issue by yutxie** [heshenghuan/LSTM-NER#14]
what do you mean by "word2vec tool standard output format"?
and where can i find them? i've only got a binary file with google's implementation of word2vec..

**Comment by heshenghuan** [comment]
Sorry, only the text file of google's word2vec is supported now.

**Comment by yutxie** [comment]
could you please tell me where to find the text file of google's word2vec?

**Comment by heshenghuan** [comment]
Actually, those files are very easy to find over the Internet(just search word embedding). Even you can try to train a word2vec with your own corpus.
