### ISSUE TITLE
how to get the dataset

### ISSUE THREAD

**Issue by loveJasmine** [heshenghuan/LSTM-NER#5]

**Comment by heshenghuan** [comment]
@loveJasmine 
Thank you for being interested about this project.

Actually, this is a general class of sequential tagger for NER or any other sequence labeling task.
So I didn't upload any dataset in this repo, you can use your own dataset if you already had one.

But if you want some dataset, maybe you can check this repo [hltcode/golden-horse](https://github.com/hltcoe/golden-horse).

Hope it helps you.:blush:
